version: '3.7'
services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: event_manager
      POSTGRES_PASSWORD: ${DATABASE_PW}
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
  web:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - .:/opt/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    restart: always
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - web
    restart: always
  redis:
    image: redis:6.2.6
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data
    restart: always
  management:
    image: portainer/portainer:latest
    ports:
      - "9000:9000"
    command: --admin-password ${PORTAINER_PW_HASH}
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
networks:
  local:
    driver: bridge
volumes:
  postgres:
  redis:
  portainer-data: