# Dockerfile.nginx
FROM nginx:1.21.6
COPY reverse-proxy.conf /etc/nginx/conf.d/reverse-proxy.conf
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
STOPSIGNAL SIGTERM
CMD ["nginx", "-g", "daemon off;"]
