version: '3.7'
services:
  db:
    image: postgres:14.2
    environment:
      POSTGRES_USER: event_manager
      POSTGRES_PASSWORD: test_db_password
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build:
      context: .
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - .:/opt/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
  proxy:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    ports:
      - '80:80'
    depends_on:
      - web
  redis:
    image: redis:6.2.6
    ports:
      - '6379:6379'
    volumes:
      - redis:/var/lib/redis/data
volumes:
  postgres:
  redis: